# Generated by Django 3.0 on 2019-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combined_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=30)),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('items', models.CharField(max_length=20)),
            ],
        ),
    ]
